name: GitHub Events Demo
run-name: 'Example Git Hub Events'

on:
  push:
    branches:
      - main

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .

  conditional_run:
    needs: print_context
    if: github.event.head_commit.author.name == 'Random Author'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The Author is Random Author'

  conditional_run2:
    needs:
      - print_context
      - conditional_run
    if: github.event.head_commit.author.name == 'Manamohan Samal'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The Author is ${{ github.event.head_commit.author.name }}'
